spring:
  datasource:
    url: jdbc:h2:file:./h2/sample;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:


  #  jpa:
  #    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server :
  port: 8888